// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/CaseStudies.tsx": () => import("../components/mockups/CaseStudies.tsx"),
  "./components/mockups/ContactUs.tsx": () => import("../components/mockups/ContactUs.tsx"),
  "./components/mockups/InnovatrHome.tsx": () => import("../components/mockups/InnovatrHome.tsx"),
  "./components/mockups/PricingPage.tsx": () => import("../components/mockups/PricingPage.tsx"),
  "./components/mockups/ResearchTools.tsx": () => import("../components/mockups/ResearchTools.tsx"),
  "./components/mockups/WhatWeDo.tsx": () => import("../components/mockups/WhatWeDo.tsx")
};
